"""Structured, durable repository intelligence and editable Markdown views."""

from .records import (
    ComponentRecord,
    ConventionRecord,
    DecisionRecord,
    FactRecord,
    FileAssociationRecord,
    IntelligenceRecord,
    LifecycleStatusRecord,
    PrincipleRecord,
    ProjectIdentityRecord,
    RecordKind,
    RecordStatus,
    RelationshipRecord,
    WorkflowRecord,
    stable_record_id,
)
from .schema import SCHEMA_VERSION, IntelligenceValidationError, validate_document
from .store import IntelligenceStore, atomic_write_text
from .storage import (
    DEFAULT_STORAGE_MODE,
    SHAREABLE_RECORD_KINDS,
    SHAREABLE_RECORD_STATUSES,
    ShareableContentError,
    StorageMode,
    StorageScope,
    coerce_storage_mode,
    record_is_reviewable,
    scope_path,
    validate_shareable_record,
)

__all__ = [
    "ComponentRecord",
    "ConventionRecord",
    "DecisionRecord",
    "FactRecord",
    "FileAssociationRecord",
    "IntelligenceRecord",
    "IntelligenceStore",
    "IntelligenceValidationError",
    "LifecycleStatusRecord",
    "PrincipleRecord",
    "ProjectIdentityRecord",
    "RecordKind",
    "RecordStatus",
    "RelationshipRecord",
    "SCHEMA_VERSION",
    "WorkflowRecord",
    "DEFAULT_STORAGE_MODE",
    "SHAREABLE_RECORD_KINDS",
    "SHAREABLE_RECORD_STATUSES",
    "ShareableContentError",
    "StorageMode",
    "StorageScope",
    "atomic_write_text",
    "stable_record_id",
    "coerce_storage_mode",
    "record_is_reviewable",
    "scope_path",
    "validate_document",
    "validate_shareable_record",
]
