"""Structured, durable repository intelligence and editable Markdown views."""

from .decisions import (
    Decision, DecisionCandidate, DecisionConflict, DecisionService, DecisionStatus, execute_decision_command, stable_decision_id,
)
from .graph import (
    DependencyGraph,
    EdgeKind,
    Evidence,
    GraphEdge,
    GraphNode,
    GraphQuery,
    JavaScriptParserAdapter,
    NodeKind,
    ParserAdapter,
    PythonAstAdapter,
    SourceLocation,
    apply_semantic_enrichment,
    build_dependency_graph,
    render_architecture,
)
from .records import (
    ComponentRecord,
    ConventionRecord,
    DecisionRecord,
    FactRecord,
    FileAssociationRecord,
    IntelligenceRecord,
    LifecycleStatusRecord,
    PrincipleRecord,
    ProjectIdentityRecord,
    RecordKind,
    RecordStatus,
    RelationshipRecord,
    WorkflowRecord,
    stable_record_id,
)
from .schema import SCHEMA_VERSION, IntelligenceValidationError, validate_document
from .store import IntelligenceStore, atomic_write_text
from .storage import (
    DEFAULT_STORAGE_MODE,
    SHAREABLE_RECORD_KINDS,
    SHAREABLE_RECORD_STATUSES,
    ShareableContentError,
    StorageMode,
    StorageScope,
    coerce_storage_mode,
    record_is_reviewable,
    scope_path,
    validate_shareable_record,
)

__all__ = [
    "Decision",
    "DecisionCandidate",
    "DecisionConflict",
    "DecisionService",
    "DecisionStatus",
    "stable_decision_id",
    "execute_decision_command",
    "DependencyGraph",
    "EdgeKind",
    "Evidence",
    "GraphEdge",
    "GraphNode",
    "GraphQuery",
    "JavaScriptParserAdapter",
    "NodeKind",
    "ParserAdapter",
    "PythonAstAdapter",
    "SourceLocation",
    "apply_semantic_enrichment",
    "build_dependency_graph",
    "render_architecture",
    "ComponentRecord",
    "ConventionRecord",
    "DecisionRecord",
    "FactRecord",
    "FileAssociationRecord",
    "IntelligenceRecord",
    "IntelligenceStore",
    "IntelligenceValidationError",
    "LifecycleStatusRecord",
    "PrincipleRecord",
    "ProjectIdentityRecord",
    "RecordKind",
    "RecordStatus",
    "RelationshipRecord",
    "SCHEMA_VERSION",
    "WorkflowRecord",
    "DEFAULT_STORAGE_MODE",
    "SHAREABLE_RECORD_KINDS",
    "SHAREABLE_RECORD_STATUSES",
    "ShareableContentError",
    "StorageMode",
    "StorageScope",
    "atomic_write_text",
    "stable_record_id",
    "coerce_storage_mode",
    "record_is_reviewable",
    "scope_path",
    "validate_document",
    "validate_shareable_record",
]
